import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Trello Mini",
  description: "Generated by Hung Tuan",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">{children}</body>
    </html>
  );
}
